### ISSUE TITLE
Possible to respond differently based on order of calls?

### ISSUE THREAD

**Issue by mrchief** [axios/moxios#39]
Trying to test retry logic of a method, so I've it wired up like this:

```js
    moxios.wait(() => {
      const request = moxios.requests.at(0)
      request.respondWith({
        status: 401
        , response: mockApiError
      })

      const nextRequest = moxios.requests.at(1)
      nextRequest.respondWith({
        status: 200
        , response: mockApiResponse
      })
    })

    const mockRequest = {
      headers: {}
      , method: 'get'
      , url: 'to/no/where'
    }

    const response = await tryMakeRequest(mockRequest)

    expect(response.status).toBe(200)
    expect(response.data).toEqual(mockApiResponse)
```

The test fails with this error:

```
    Timeout - Async callback was not invoked within timeout specified by
jasmine.DEFAULT_TIMEOUT_INTERVAL.

      at node_modules/jest-jasmine2/build/queue_runner.js:64:21
      at Timeout.callback [as _onTimeout] (node_modules/jsdom/lib/jsdom/browser/Window.js:523:19)
      at ontimeout (timers.js:469:11)
      at tryOnTimeout (timers.js:304:5)
      at Timer.listOnTimeout (timers.js:264:5)
```

Any ideas what am I missing here?

**Comment by mrchief** [comment]
For the time being, I'm using `axios-mock-adapter` and this works:

```js
    mock.onGet('/to/no/where').replyOnce(401, mockApiError)
      .onGet('/to/no/where').replyOnce(200, mockApiResponse)
```

**Comment by anilanar** [comment]
Kamino cloned this issue to anilanar/moxios

**Comment by omrilotan** [comment]
Couldn't find a resolution for this. This is how I addressed this issue, if it helps the next poor soul:

In this example, the same route fails the first time, then succeeds for subsequent requests. This logic can be expanded to check anything from authentication flow to rate limit
```js
// Initial setup
class MockResponse {
  constructor() {
      this.iterations = 0;
  }
  get status() {
      return this.iterations++ === 0 ? 403 : 200;
  }
  get response() {
      return 'Something, anything';
  }
}

// Register in beforeEach
moxios.stubRequest('/route', new MockResponse());

// First call fails: gets 403
expect(axios.get('/route')).rejects.toThrow('Request failed with status code 404');

// The next one's okay: gets 200
const { status } = await axios.get(REQUEST_PERIMETERX_BLOCK);
expect(status).toBe(200);
```

**Comment by veryneatperson** [comment]
**omrilotan**, thanks a lot. 
Kinda hard to find reasonable solutions for that.
It really works (even though feels kinda unnatural).

By the way, as i understand, moxios.stubRequest first calls _get response_ and then _get status_.

**Comment by omrilotan** [comment]
@veryneatperson You're right
https://github.com/axios/moxios/blob/3785075af9a740fa6071510f882b38d3fa62be64/index.js#L268-L269
I'll switch them in the comment

**Comment by Peter-Hudson** [comment]
Slightly different take:
```
// different responses
function* responses() {
        yield { status: 401, response: { description: 'errored' } };
        yield { status: 200, response: { description: 'success' } };
      }

      const gen = responses();
     
      moxios.stubRequest('/route', gen.next().value);
```
