### ISSUE TITLE
moxios.requests.mostRecent() is returning undefined

### ISSUE THREAD

**Issue by reactsaurabh** [axios/moxios#78]
I am using Webpack in React and after running test getting below error 
   
Error: Uncaught [TypeError: Cannot read property 'respondWith' of undefined]
          at reportException (/Users/saurabh/Desktop/project/rewards-app-fe/node_modules/jsdom/lib/jsdom/living/helpers/runtime-script-errors.js:66:24)
          at Timeout.callback [as _onTimeout] (/Users/saurabh/Desktop/project/rewards-app-fe/node_modules/jsdom/lib/jsdom/browser/Window.js:680:7)
          at listOnTimeout (internal/timers.js:549:17)
          at processTimers (internal/timers.js:492:7) TypeError: Cannot read property 'respondWith' of undefined
          at /Users/saurabh/Desktop/project/rewards-app-fe/src/Store/Actions/AuthActions/AuthActions.test.js:35:15
          at Timeout.callback [as _onTimeout] (/Users/saurabh/Desktop/project/rewards-app-fe/node_modules/jsdom/lib/jsdom/browser/Window.js:678:19)
          at listOnTimeout (internal/timers.js:549:17)
          at processTimers (internal/timers.js:492:7)

**Comment by andyngdz** [comment]
Getting same issue

**Comment by hai-nguyen1112** [comment]
I am having the same issue.

**Comment by Proxi01** [comment]
any updates? Stuck with the same problem

**Comment by Mitdd9707** [comment]
I am having the same issue.

**Comment by sinfonico7** [comment]
The same here...

**Comment by orenfromberg** [comment]
saaaaame

**Comment by Iddy123** [comment]
samee

**Comment by tanmayVaish** [comment]
same

**Comment by parvathirajan** [comment]
+1
